### ISSUE TITLE
casa-python casa-tools requires ncurses 5.9?

### ISSUE THREAD

**Issue by caseyjlaw** [pkgw/pwkit#9]
I'm caught in another dependency trap. It seems that most packages require ncurses 6.0, but casa-python and casa-tools requires 5.9. E.g., with a fresh environment:
```
gygax$ conda install ipython casa-python pwkit cython jupyter dask pandas distributed casacore astropy cfitsio numpy scipy numba bokeh matplotlib
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - casa-python -> casa-tools 4.7.* -> casacore 2.2.* -> ncurses 5.9*
  - libedit
Use "conda info <package>" to see the dependencies for each package.
```

Suggestions?

**Comment by caseyjlaw** [comment]
Looking a bit deeper, it seems that libedit is a *conda* dependency and it conflicts with ncurses=5.9. Conda isn't really clear about this, but it seems to arise when using the root environment. They have a new dependency solver, so that may explain why it started recently.
My workaround (still under way) is to have everything in a conda environment. That seems to avoid the issue. But if ncurses=6.0 is ok for casa stuff, it would be nice to allow higher versions than 5.9 in the dependencies.

**Comment by pkgw** [comment]
Yeah, so this is fallout from the recent release of Anaconda 5.0, which upgrades all sorts of dependencies across the ecosystem. As far as I can tell, conda-forge hasn't yet caught up, especially with binary dependencies because the compilers have changed.

If this is urgent it might be possible to develop a workaround, but I think this is just going to take some time for conda-forge to catch up with the main Anaconda channel. The changes look pretty wide-ranging, though, so I expect that will take a while.

One approach that we've been using with Travis CI on HERA projects is to remove the "defaults" channel from the Conda configuration and just use "conda-forge". This maintains a self-consistent stack that doesn't use the newer packages. There are a handful of packages provided in "defaults" that conda-forge doesn't provide; so far the only one that's popped up in this context has been "libgfortran".

**Comment by caseyjlaw** [comment]
Thanks. I did notice a ton of recent issues that looked like mine.
I've worked around this by not using the root environment. It works (and is probably better practice). I'll close this.
